services:
  myapp:
    image: myapp:1
    restart: unless-stopped # Redémarre le conteneur sauf si arrêté manuellement
    ports:
      - "8080:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16  # Version spécifique et légère de Postgres 16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # Vérification de la santé du conteneur Postgres
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"] # Vérifie si Postgres est prêt
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt